services:
  db:
    image: postgres:13.13
    environment:
      POSTGRES_PASSWORD: doNotUseThisPasswordInARealApplication
      POSTGRES_DB: simple-form-db
    ports:
      - 5432:5432
    networks:
      - simple-form-net

networks:
  simple-form-net:
